
package com.mycompany.totemmuseo.apresentacao;

import com.mycompany.totemmuseo.modelo.*;



public class frmPrincipal extends javax.swing.JDialog
{
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmPrincipal.class.getName());

    /**
     * Creates new form frmPrincipal
     * @param parent
     * @param modal
     */
    public frmPrincipal(java.awt.Frame parent, boolean modal)
    {
        super(parent, modal);
        initComponents();
    }
    public frmPrincipal() 
    {
        super((java.awt.Frame)null,true);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        lblApresentacao = new javax.swing.JLabel();
        lblsojournerFoto = new javax.swing.JLabel();
        lblTituloSojourner = new javax.swing.JLabel();
        lblSpiritOpportunityFoto = new javax.swing.JLabel();
        lblTituloSpiritOpportunity = new javax.swing.JLabel();
        lblCuriosityFoto = new javax.swing.JLabel();
        lblTituloCuriosity = new javax.swing.JLabel();
        lblFotoPerseverance = new javax.swing.JLabel();
        lblTituloPerseverance = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Totem Museo Espacial");

        lblApresentacao.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblApresentacao.setText("<html>Bem-vindo ao museu espacial, aqui você irá descobrir um pouco sobre os robôs exploradores criados para uma missão importante de descobrir e analisar o planeta Marte. Abaixo você vai ver as fotos dos robôs e, se clicar nelas, vai conhecer um pouco da história de cada um.");

        lblsojournerFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ASY-SA0723_07-Sojourner-rover.jpg"))); // NOI18N
        lblsojournerFoto.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                lblsojournerFotoMouseClicked(evt);
            }
        });

        lblTituloSojourner.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblTituloSojourner.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloSojourner.setText("Sojourner");

        lblSpiritOpportunityFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/spiriteOpportunity.jpg"))); // NOI18N
        lblSpiritOpportunityFoto.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                lblSpiritOpportunityFotoMouseClicked(evt);
            }
        });

        lblTituloSpiritOpportunity.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblTituloSpiritOpportunity.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloSpiritOpportunity.setText("Spirit e Opportunity");

        lblCuriosityFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/_100519152_2.jpg"))); // NOI18N
        lblCuriosityFoto.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                lblCuriosityFotoMouseClicked(evt);
            }
        });

        lblTituloCuriosity.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblTituloCuriosity.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloCuriosity.setText("Curiosity");

        lblFotoPerseverance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/_118653459_watsel_1_face_full.jpg (1).jpg"))); // NOI18N
        lblFotoPerseverance.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                lblFotoPerseveranceMouseClicked(evt);
            }
        });

        lblTituloPerseverance.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblTituloPerseverance.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloPerseverance.setText("Perseverance");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblApresentacao, javax.swing.GroupLayout.DEFAULT_SIZE, 1424, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblsojournerFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblTituloSojourner, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblSpiritOpportunityFoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTituloSpiritOpportunity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblCuriosityFoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTituloCuriosity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblFotoPerseverance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTituloPerseverance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(22, 22, 22))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblApresentacao, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTituloSojourner, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(lblTituloSpiritOpportunity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTituloCuriosity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTituloPerseverance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblFotoPerseverance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCuriosityFoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSpiritOpportunityFoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblsojournerFoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(240, 240, 240))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblsojournerFotoMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lblsojournerFotoMouseClicked
    {//GEN-HEADEREND:event_lblsojournerFotoMouseClicked
        Sojourner sojourner = new Sojourner();
        sojourner.abrirTelaSojourner(this);
    }//GEN-LAST:event_lblsojournerFotoMouseClicked

    private void lblSpiritOpportunityFotoMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lblSpiritOpportunityFotoMouseClicked
    {//GEN-HEADEREND:event_lblSpiritOpportunityFotoMouseClicked
        spirit_Opportunity spirityopportunity = new spirit_Opportunity();
        spirityopportunity.abrirTelaSpiritOpportunity(this);
    }//GEN-LAST:event_lblSpiritOpportunityFotoMouseClicked

    private void lblCuriosityFotoMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lblCuriosityFotoMouseClicked
    {//GEN-HEADEREND:event_lblCuriosityFotoMouseClicked
        curiosity Curiosity = new curiosity();
        Curiosity.abrirTelaCuriosity(this);
    }//GEN-LAST:event_lblCuriosityFotoMouseClicked

    private void lblFotoPerseveranceMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lblFotoPerseveranceMouseClicked
    {//GEN-HEADEREND:event_lblFotoPerseveranceMouseClicked
        Perseverance perseverance = new Perseverance();
        perseverance.abrirTelaPerseverance(this);
    }//GEN-LAST:event_lblFotoPerseveranceMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex)
        {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() ->
        {
            frmPrincipal dialog = new frmPrincipal(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter()
            {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e)
                {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblApresentacao;
    private javax.swing.JLabel lblCuriosityFoto;
    private javax.swing.JLabel lblFotoPerseverance;
    private javax.swing.JLabel lblSpiritOpportunityFoto;
    private javax.swing.JLabel lblTituloCuriosity;
    private javax.swing.JLabel lblTituloPerseverance;
    private javax.swing.JLabel lblTituloSojourner;
    private javax.swing.JLabel lblTituloSpiritOpportunity;
    private javax.swing.JLabel lblsojournerFoto;
    // End of variables declaration//GEN-END:variables
}
